spring.profiles.active: dev
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    distribution:
      sla:
        http:
          server:
            requests: "10ms,30ms,50ms,100ms,150ms,250ms,500ms,1s"
      percentiles-histogram:
        http:
          server:
            requests: true
    web:
      server:
        request:
          autotime:
            enabled: true
    export:
      prometheus:
        enabled: true
    tags:
      application: prometheus-demo



#最大连接数
http.maxTotal: 400
  #并发数
http.defaultMaxPerRoute: 200
  #创建连接的最长时间
http.connectTimeout: 1000
  #从连接池中获取到连接的最长时间
http.connectionRequestTimeout: 500
  #数据传输的最长时间
http.socketTimeout: 1000
  #提交请求前测试连接是否可用
http.staleConnectionCheckEnabled: true
---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: test


